"""Persistence layer (§12). ORM models and repositories live here only.

Services and agent logic depend on repository protocols (DB-005), never on
`sqlalchemy` directly — this package is where that boundary is drawn.
"""

from app.persistence.base import MOCK_CRM_SCHEMA, OPSPILOT_SCHEMA, Base
from app.persistence.mock_crm import (
    Company,
    Customer,
    CustomerStatus,
    EmailOutbox,
    EmailOutboxStatus,
    Lead,
    LeadStatus,
    OutreachDraft,
    OutreachDraftStatus,
)
from app.persistence.models import (
    AgentRun,
    ApprovalRow,
    EvaluationResult,
    EvaluationRun,
    EvaluationRunStatus,
    ExecutionStep,
    ToolCallRow,
    ToolCallStatus,
    TraceEvent,
    TraceEventKind,
    TraceEventSeverity,
)
from app.persistence.protocols import (
    AgentRunRepository,
    ApprovalRepository,
    ApprovalUpsert,
    CompanyRepository,
    CustomerRepository,
    EmailOutboxRepository,
    EvaluationRepository,
    ExecutionStepRepository,
    LeadRepository,
    OutreachDraftRepository,
    ToolCallRepository,
    TraceEventRepository,
    UnitOfWork,
)
from app.persistence.repositories import (
    SqlAgentRunRepository,
    SqlApprovalRepository,
    SqlCompanyRepository,
    SqlCustomerRepository,
    SqlEmailOutboxRepository,
    SqlEvaluationRepository,
    SqlExecutionStepRepository,
    SqlLeadRepository,
    SqlOutreachDraftRepository,
    SqlToolCallRepository,
    SqlTraceEventRepository,
    SqlUnitOfWork,
)
from app.persistence.session import (
    create_session_factory,
    unit_of_work,
)

__all__ = [
    "MOCK_CRM_SCHEMA",
    "OPSPILOT_SCHEMA",
    "AgentRun",
    "AgentRunRepository",
    "ApprovalRepository",
    "ApprovalRow",
    "ApprovalUpsert",
    "Base",
    "Company",
    "CompanyRepository",
    "Customer",
    "CustomerRepository",
    "CustomerStatus",
    "EmailOutbox",
    "EmailOutboxRepository",
    "EmailOutboxStatus",
    "EvaluationRepository",
    "EvaluationResult",
    "EvaluationRun",
    "EvaluationRunStatus",
    "ExecutionStep",
    "ExecutionStepRepository",
    "Lead",
    "LeadRepository",
    "LeadStatus",
    "OutreachDraft",
    "OutreachDraftRepository",
    "OutreachDraftStatus",
    "SqlAgentRunRepository",
    "SqlApprovalRepository",
    "SqlCompanyRepository",
    "SqlCustomerRepository",
    "SqlEmailOutboxRepository",
    "SqlEvaluationRepository",
    "SqlExecutionStepRepository",
    "SqlLeadRepository",
    "SqlOutreachDraftRepository",
    "SqlToolCallRepository",
    "SqlTraceEventRepository",
    "SqlUnitOfWork",
    "ToolCallRow",
    "ToolCallRepository",
    "ToolCallStatus",
    "TraceEvent",
    "TraceEventKind",
    "TraceEventRepository",
    "TraceEventSeverity",
    "UnitOfWork",
    "create_session_factory",
    "unit_of_work",
]
