/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/approvals/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approval Queue
         * @description Return pending approvals ordered deterministically for operator review.
         */
        get: operations["list_approval_queue_api_v1_approvals_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Approval
         * @description Retrieve a single approval by its UUID.
         */
        get: operations["get_approval_api_v1_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Approval
         * @description Record a human operator's decision and safely resume the execution graph.
         *
         *     Passes the caller's exact `args_hash` to `ApprovalService.decide_approval(...)`.
         *     The database conditional update resolves races and idempotency.
         */
        post: operations["decide_approval_api_v1_approvals__approval_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation Metrics
         * @description Return the §15.4 metric snapshot of the most recent matching run.
         *
         *     An empty `metrics` object (with `evaluation_run_id: null`) means no run
         *     has been recorded yet — never a fabricated zero-valued snapshot.
         */
        get: operations["get_evaluation_metrics_api_v1_evaluations_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evaluation Runs
         * @description Return evaluation runs, most recently started first (§12.8).
         */
        get: operations["list_evaluation_runs_api_v1_evaluations_runs_get"];
        put?: never;
        /**
         * Create Evaluation Run
         * @description Start a suite run. Returns immediately with the `running` row; the
         *     suite executes in the background and completes the row as the CLI does.
         */
        post: operations["create_evaluation_run_api_v1_evaluations_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs/{evaluation_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Run */
        get: operations["get_evaluation_run_api_v1_evaluations_runs__evaluation_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs/{evaluation_run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evaluation Results
         * @description Return every case result for one evaluation run, ordered by case id.
         */
        get: operations["list_evaluation_results_api_v1_evaluations_runs__evaluation_run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List runs with optional filtering and keyset cursor pagination (§13.2).
         */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Create a new durable run or return the existing run on idempotent replay (§13.2).
         */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Retrieve full run details including execution steps and pending approval (§13.3).
         */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Cooperatively cancel an active or non-terminal run (§13.2).
         */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description Stream live trace events via Server-Sent Events (SSE) with Last-Event-ID replay (§13.4).
         */
        get: operations["stream_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Run
         * @description Create a new run linked to parent run_id, copying user_request (§10.6, §13.2).
         */
        post: operations["retry_run_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Transition a run from created to queued and schedule execution (§13.2).
         */
        post: operations["start_run_api_v1_runs__run_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Trace
         * @description Retrieve paginated execution trace events ordered strictly by monotonic seq (§13.4).
         */
        get: operations["get_run_trace_api_v1_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tools
         * @description Return every registered tool contract (§8.2), in registry order.
         */
        get: operations["list_tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approval Queue
         * @description Return pending approvals ordered deterministically for operator review.
         */
        get: operations["list_approval_queue_approvals_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Approval
         * @description Retrieve a single approval by its UUID.
         */
        get: operations["get_approval_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approval_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Approval
         * @description Record a human operator's decision and safely resume the execution graph.
         *
         *     Passes the caller's exact `args_hash` to `ApprovalService.decide_approval(...)`.
         *     The database conditional update resolves races and idempotency.
         */
        post: operations["decide_approval_approvals__approval_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation Metrics
         * @description Return the §15.4 metric snapshot of the most recent matching run.
         *
         *     An empty `metrics` object (with `evaluation_run_id: null`) means no run
         *     has been recorded yet — never a fabricated zero-valued snapshot.
         */
        get: operations["get_evaluation_metrics_evaluations_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evaluation Runs
         * @description Return evaluation runs, most recently started first (§12.8).
         */
        get: operations["list_evaluation_runs_evaluations_runs_get"];
        put?: never;
        /**
         * Create Evaluation Run
         * @description Start a suite run. Returns immediately with the `running` row; the
         *     suite executes in the background and completes the row as the CLI does.
         */
        post: operations["create_evaluation_run_evaluations_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/runs/{evaluation_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Run */
        get: operations["get_evaluation_run_evaluations_runs__evaluation_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/runs/{evaluation_run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evaluation Results
         * @description Return every case result for one evaluation run, ordered by case id.
         */
        get: operations["list_evaluation_results_evaluations_runs__evaluation_run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness. Process only, no dependencies (§13.7).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List runs with optional filtering and keyset cursor pagination (§13.2).
         */
        get: operations["list_runs_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Create a new durable run or return the existing run on idempotent replay (§13.2).
         */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Retrieve full run details including execution steps and pending approval (§13.3).
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Cooperatively cancel an active or non-terminal run (§13.2).
         */
        post: operations["cancel_run_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description Stream live trace events via Server-Sent Events (SSE) with Last-Event-ID replay (§13.4).
         */
        get: operations["stream_run_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Run
         * @description Create a new run linked to parent run_id, copying user_request (§10.6, §13.2).
         */
        post: operations["retry_run_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Transition a run from created to queued and schedule execution (§13.2).
         */
        post: operations["start_run_runs__run_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Trace
         * @description Retrieve paginated execution trace events ordered strictly by monotonic seq (§13.4).
         */
        get: operations["get_run_trace_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tools
         * @description Return every registered tool contract (§8.2), in registry order.
         */
        get: operations["list_tools_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApprovalDecisionKind
         * @enum {string}
         */
        ApprovalDecisionKind: "approve" | "reject";
        /**
         * ApprovalDecisionRequest
         * @description Operator decision payload for POST /approvals/{approval_id}/decision.
         */
        ApprovalDecisionRequest: {
            /**
             * Args Hash
             * @description Canonical SHA-256 hash the operator saw (§13.5). Optional but recommended: when supplied it must equal the persisted hash exactly, else 409 approval_superseded.
             */
            args_hash?: string | null;
            /**
             * Decided By
             * @description Client attribution.
             */
            decided_by?: string | null;
            decision: components["schemas"]["ApprovalDecisionKind"];
            /**
             * Reason
             * @description Operator reason.
             */
            reason?: string | null;
        };
        /**
         * ApprovalResource
         * @description Safe external representation of an approval awaiting or settled by human decision.
         */
        ApprovalResource: {
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /** Args Hash */
            args_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Payload Preview */
            payload_preview: {
                [key: string]: unknown;
            };
            /** Reason */
            reason?: string | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Risk */
            risk: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["ApprovalStatus"];
            /** Step Id */
            step_id: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Tool */
            tool: string;
        };
        /**
         * ApprovalStatus
         * @enum {string}
         */
        ApprovalStatus: "pending" | "approved" | "rejected" | "expired" | "superseded" | "cancelled";
        /**
         * EvaluationMetricsResponse
         * @description GET /evaluations/metrics — the §15.4 snapshot of the latest matching run.
         *
         *     Not a new computation: `metrics` is copied verbatim from the most recent
         *     `evaluation_runs.metrics` (optionally filtered by `suite`), the same
         *     JSONB the runner (EVAL-003) already wrote.
         */
        EvaluationMetricsResponse: {
            /** Evaluation Run Id */
            evaluation_run_id?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Suite */
            suite?: string | null;
        };
        /**
         * EvaluationResultResource
         * @description One `evaluation_results` row (§12.8) — a single case's outcome.
         */
        EvaluationResultResource: {
            /** Approval Outcome */
            approval_outcome?: string | null;
            /** Assertions */
            assertions?: {
                [key: string]: unknown;
            }[];
            /** Case Id */
            case_id: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Evaluation Run Id
             * Format: uuid
             */
            evaluation_run_id: string;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Passed */
            passed: boolean;
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /** Retry Count */
            retry_count: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Tool Calls Count */
            tool_calls_count: number;
        };
        /**
         * EvaluationRunCreateRequest
         * @description Payload for POST /evaluations/runs.
         */
        EvaluationRunCreateRequest: {
            /**
             * Suite
             * @description Suite name declared in evals/suites.yaml.
             * @default all
             */
            suite: string;
        };
        /** EvaluationRunListResponse */
        EvaluationRunListResponse: {
            /** Items */
            items: components["schemas"]["EvaluationRunResource"][];
        };
        /**
         * EvaluationRunResource
         * @description One `evaluation_runs` row (§12.8).
         */
        EvaluationRunResource: {
            /** Case Count */
            case_count: number;
            /**
             * Evaluation Run Id
             * Format: uuid
             */
            evaluation_run_id: string;
            /** Failed */
            failed: number;
            /** Finished At */
            finished_at?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Model Id */
            model_id?: string | null;
            /** Passed */
            passed: number;
            planner_kind: components["schemas"]["PlannerKind"];
            /** Prompt Version */
            prompt_version?: string | null;
            /** Seed */
            seed?: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["EvaluationRunStatus"];
            /** Suite */
            suite: string;
        };
        /**
         * EvaluationRunStatus
         * @description §12.8 — one suite execution's lifecycle. Distinct from `RunStatus`,
         *     which is the *agent* run each case drives, not the suite itself.
         * @enum {string}
         */
        EvaluationRunStatus: "running" | "completed" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlannerKind
         * @enum {string}
         */
        PlannerKind: "rules" | "llm";
        /**
         * RunCancelRequest
         * @description Optional payload for POST /runs/{run_id}/cancel (§13.2).
         */
        RunCancelRequest: {
            /**
             * Reason
             * @description Cancellation reason.
             */
            reason?: string | null;
        };
        /**
         * RunCounters
         * @description Denormalized execution counters for a run (§13.3).
         */
        RunCounters: {
            /**
             * Replan Count
             * @default 0
             */
            replan_count: number;
            /**
             * Retry Total
             * @default 0
             */
            retry_total: number;
            /**
             * Step Count
             * @default 0
             */
            step_count: number;
        };
        /**
         * RunCreateRequest
         * @description Payload for POST /runs creating a new agent run (§13.2).
         */
        RunCreateRequest: {
            /**
             * Auto Start
             * @description Whether to immediately schedule execution in the background.
             * @default false
             */
            auto_start: boolean;
            /**
             * Metadata
             * @description Arbitrary client metadata.
             */
            metadata?: {
                [key: string]: unknown;
            };
            /** @description Optional planner override (rules or llm). */
            planner_kind?: components["schemas"]["PlannerKind"] | null;
            /**
             * User Request
             * @description Natural-language business request for the agent to execute.
             */
            user_request: string;
        };
        /**
         * RunListResponse
         * @description Paginated list of run summaries with keyset cursor (§13.2).
         */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total Estimate */
            total_estimate: number;
        };
        /**
         * RunPendingApproval
         * @description Public summary of a currently open approval gate on the run (§13.3).
         */
        RunPendingApproval: {
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /** Args Hash */
            args_hash: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Payload Preview */
            payload_preview: {
                [key: string]: unknown;
            };
            /** Risk */
            risk: string;
            /** Step Id */
            step_id: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Tool */
            tool: string;
        };
        /**
         * RunResource
         * @description The canonical run detail resource returned by POST /runs and GET /runs/{id} (§13.3).
         */
        RunResource: {
            counters: components["schemas"]["RunCounters"];
            /** Final Response */
            final_response?: {
                [key: string]: unknown;
            } | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Normalized Task */
            normalized_task?: {
                [key: string]: unknown;
            } | null;
            /** Parent Run Id */
            parent_run_id?: string | null;
            pending_approval?: components["schemas"]["RunPendingApproval"] | null;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Resumable */
            resumable: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Status Reason */
            status_reason?: string | null;
            /** Steps */
            steps?: components["schemas"]["RunStepSummary"][];
            timestamps: components["schemas"]["RunTimestamps"];
            /** User Request */
            user_request: string;
        };
        /**
         * RunRetryRequest
         * @description Optional payload for POST /runs/{run_id}/retry (§13.2).
         */
        RunRetryRequest: {
            /**
             * Auto Start
             * @description Whether to queue the new run immediately.
             * @default false
             */
            auto_start: boolean;
            /**
             * Metadata
             * @description Metadata override for child run.
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "created" | "queued" | "running" | "awaiting_approval" | "completed" | "failed" | "rejected" | "cancelled" | "expired";
        /**
         * RunStepSummary
         * @description Public summary of a single execution step instance (§13.3).
         */
        RunStepSummary: {
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /** Seq */
            seq: number;
            /** Status */
            status: string;
            /** Step Id */
            step_id: string;
            /** Tool */
            tool: string;
            /** Verification Status */
            verification_status?: string | null;
        };
        /**
         * RunSummary
         * @description Lightweight summary of a run for listing and operational status (§13.2, §13.3).
         */
        RunSummary: {
            counters: components["schemas"]["RunCounters"];
            /** Duration Ms */
            duration_ms?: number | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Resumable */
            resumable: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Status Reason */
            status_reason?: string | null;
            timestamps: components["schemas"]["RunTimestamps"];
            /** User Request */
            user_request: string;
        };
        /**
         * RunTimestamps
         * @description Lifecycle timestamp snapshot for a run (§13.3).
         */
        RunTimestamps: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Started At */
            started_at?: string | null;
        };
        /** ToolFailureModeResource */
        ToolFailureModeResource: {
            /** Description */
            description: string;
            /** Error Class */
            error_class: string;
        };
        /**
         * ToolResource
         * @description One entry of the `GET /tools` catalog — a contract, not a live tool.
         */
        ToolResource: {
            /** Failure Modes */
            failure_modes: components["schemas"]["ToolFailureModeResource"][];
            /** Idempotent */
            idempotent: boolean;
            /** Name */
            name: string;
            /** Nondeterministic */
            nondeterministic: boolean;
            /** Purpose */
            purpose: string;
            /** Requires Approval */
            requires_approval: boolean;
            /** Risk */
            risk: string;
            /** Schemas */
            schemas: {
                [key: string]: unknown;
            };
            /** Side Effect */
            side_effect: string;
            /** Timeout Ms */
            timeout_ms: number;
            /** Untrusted Output */
            untrusted_output: boolean;
            /** Verification */
            verification: string;
            /** Version */
            version: string;
        };
        /**
         * TraceEventKind
         * @description §14.2 — the fixed vocabulary of product-trace events.
         *
         *     Structural (§14.4): `@traced_node`, `ToolRegistry.dispatch` and the
         *     DB-007 reconciler are the only emitters, so this list is exactly what
         *     those choke points can ever produce, not an open vocabulary a future
         *     call site might extend ad hoc.
         * @enum {string}
         */
        TraceEventKind: "run_created" | "run_started" | "run_completed" | "run_failed" | "run_rejected" | "run_expired" | "run_cancelled" | "node_entered" | "node_exited" | "plan_created" | "plan_revised" | "fanout_expanded" | "tool_started" | "tool_succeeded" | "tool_failed" | "tool_timeout" | "tool_duplicate_suppressed" | "retry_scheduled" | "step_skipped" | "budget_exhausted" | "approval_requested" | "approval_granted" | "approval_rejected" | "approval_expired" | "approval_superseded" | "verification_passed" | "verification_failed" | "verification_skipped" | "policy_violation" | "run_recovered";
        /**
         * TraceEventResource
         * @description Public, safe representation of a durable trace event (§13.4, §14.3).
         */
        TraceEventResource: {
            /** Attempt */
            attempt?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /** Input */
            input?: {
                [key: string]: unknown;
            } | null;
            kind: components["schemas"]["TraceEventKind"];
            /** Node */
            node?: string | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Retry Count */
            retry_count?: number | null;
            /** Seq */
            seq: number;
            severity: components["schemas"]["TraceEventSeverity"];
            /** Status */
            status?: string | null;
            /** Step Id */
            step_id?: string | null;
            /** Tool */
            tool?: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /**
         * TraceEventSeverity
         * @description §12.7 — always `error` for `policy_violation` (§14.2).
         * @enum {string}
         */
        TraceEventSeverity: "debug" | "info" | "warning" | "error";
        /**
         * TraceResponse
         * @description Paginated trace envelope (§13.4).
         */
        TraceResponse: {
            /** Complete */
            complete: boolean;
            /** Events */
            events: components["schemas"]["TraceEventResource"][];
            /** Next Seq */
            next_seq?: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_approval_queue_api_v1_approvals_queue_get: {
        parameters: {
            query?: {
                /** @description Max pending approvals to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_api_v1_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_api_v1_approvals__approval_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_metrics_api_v1_evaluations_metrics_get: {
        parameters: {
            query?: {
                /** @description Restrict to the latest run of one suite. */
                suite?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_runs_api_v1_evaluations_runs_get: {
        parameters: {
            query?: {
                /** @description Filter to one suite. */
                suite?: string | null;
                /** @description Max runs to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_run_api_v1_evaluations_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_run_api_v1_evaluations_runs__evaluation_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_results_api_v1_evaluations_runs__evaluation_run_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResultResource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"][] | null;
                since?: string | null;
                until?: string | null;
                parent_run_id?: string | null;
                q?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunCancelRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                /** @description Fallback starting sequence if Last-Event-ID is absent. */
                since_seq?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunRetryRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_runs__run_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_trace_api_v1_runs__run_id__trace_get: {
        parameters: {
            query?: {
                /** @description Inclusive sequence start cursor (seq >= since_seq). */
                since_seq?: number;
                /** @description Max events to return per page. */
                limit?: number;
                /** @description Filter by event kind (repeatable). */
                kind?: components["schemas"]["TraceEventKind"][] | null;
                /** @description Filter by minimum severity level. */
                severity_min?: components["schemas"]["TraceEventSeverity"] | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResource"][];
                };
            };
        };
    };
    list_approval_queue_approvals_queue_get: {
        parameters: {
            query?: {
                /** @description Max pending approvals to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_approvals__approval_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_metrics_evaluations_metrics_get: {
        parameters: {
            query?: {
                /** @description Restrict to the latest run of one suite. */
                suite?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_runs_evaluations_runs_get: {
        parameters: {
            query?: {
                /** @description Filter to one suite. */
                suite?: string | null;
                /** @description Max runs to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_run_evaluations_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_run_evaluations_runs__evaluation_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_results_evaluations_runs__evaluation_run_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResultResource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"][] | null;
                since?: string | null;
                until?: string | null;
                parent_run_id?: string | null;
                q?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunCancelRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_runs__run_id__events_get: {
        parameters: {
            query?: {
                /** @description Fallback starting sequence if Last-Event-ID is absent. */
                since_seq?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunRetryRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_runs__run_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_trace_runs__run_id__trace_get: {
        parameters: {
            query?: {
                /** @description Inclusive sequence start cursor (seq >= since_seq). */
                since_seq?: number;
                /** @description Max events to return per page. */
                limit?: number;
                /** @description Filter by event kind (repeatable). */
                kind?: components["schemas"]["TraceEventKind"][] | null;
                /** @description Filter by minimum severity level. */
                severity_min?: components["schemas"]["TraceEventSeverity"] | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResource"][];
                };
            };
        };
    };
}
